#export XDG_CONFIG_HOME="/home/mcampbell/.config"
set -x

~/.dropbox-dist/dropboxd &

# get colours right
xrdb -load ~/.Xresources

# start vrome server so we can have vim as chromium editor
nohup vrome > /dev/null &

#screensaver
xscreensaver -nosplash &

# we gonna do some work ??

xterm &
xterm &

# start the multiple madness
synergys &

# start WM
awesome

